name: Event Loggger
on:
  push:
    branches:
    - dev

jobs:

  log-github-event-goodies:
    name: "LOG git commit"
    runs-on: ubuntu-latest
    steps:
      - name: Show commit id
        run: echo "${{github.event.head_commit.id}}"
      
      - name: show GITHUB_SHA
        run: echo $GITHUB_SHA
        
  pull-request:
    name: "Make Pull Request"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: dev
        destination_branch: main
        pr_title: "Auto merge DEV into MAIN"
        github_token: ${{ secrets.GITHUB_TOKEN }}
