name: Event Loggger
on:
  push:
    branches:
    - main

jobs:

  log-github-event-goodies:
    name: "LOG git commit"
    runs-on: ubuntu-latest
    steps:
      - name: Show commit id
        run: echo "${{toJson(event.github.commits)}}"
        
      - name: show GITHUB_SHA
        run: echo $GITHUB_SHA
