name: Event Loggger
on:
  push:
    branches:
    - main

jobs:

  job-var-text:
    name: set the job level var with text
    runs-on: ubuntu-latest
    outputs: 
      var: "from simple text"
      
  job-var-step:
    name: set the job level var from step
    runs-on: ubuntu-latest
    outputs: 
      var: ${{ steps.set_var.outputs.var }}
      
  
    steps:
      - name: set step var
        id: set_var
        run: echo "::set-output name=var::from_step"
  
  
  job-output:
    name: output vars
    runs-on: ubuntu-latest
    needs: [ job-var-text, job-var-step ]
    
    steps:
      - name: var from text
        run: echo ${{ needs.job-var-text.outputs.var}}
  
      - name: var from calculation
        run: echo ${{ needs.job-var-step.outputs.var}}

      - name: Show commit id
        run: echo "${{github.event.commits[1].id}}"

      - name: show GITHUB_SHA
        run: echo $GITHUB_SHA