name: Event Loggger
on:
  push:
    branches:
    - main

jobs:

  log-github-event-goodies:
    name: "LOG git commit"
    runs-on: ubuntu-latest
    steps:

      - name: Show event
        run: echo "${{toJson(github.event)}}"
        
      - name: show GITHUB_SHA
        run: echo $GITHUB_SHA
