name: Event Loggger
on: push

jobs:
  log-github-event-goodies:
    name: "LOG git commit"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: echo "${{github.event.head_commit.id}}"
